# Generated by Django 5.0.4 on 2024-04-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="link_video",
            field=models.URLField(
                blank=True, max_length=100, null=True, verbose_name="Ссылка на видео"
            ),
        ),
    ]
