# Generated by Django 5.0.4 on 2024-04-30 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_alter_lesson_link_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=35, verbose_name="Названия"),
        ),
    ]
