# Generated by Django 5.0.4 on 2024-04-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_alter_course_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="title",
            field=models.CharField(max_length=35, verbose_name="Названия"),
        ),
    ]
