# Generated by Django 5.0.4 on 2024-04-30 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_alter_lesson_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="materials.lesson",
                verbose_name="Урок",
            ),
        ),
    ]
