# Generated by Django 5.0.4 on 2024-05-01 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_alter_course_lesson"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="lesson",
        ),
        migrations.AddField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="materials.course",
                verbose_name="Курс",
            ),
        ),
    ]
